### ISSUE TITLE
There should be a return button after checkout

### ISSUE THREAD

**Issue by A0135867R** [rongxin/se23_p01#12]
![return button](https://cloud.githubusercontent.com/assets/11241264/6881022/efbd1cca-d587-11e4-96da-51a0c7ce7cae.PNG)

**Comment by rongxin** [comment]
Ready for verification.

**Comment by A0135867R** [comment]
During checkout, it should be displayed as "Cancel"; after checkout, it should be checked to "Return"

**Comment by rongxin** [comment]
fixed, ready for verify again.
