### ISSUE TITLE
Product description text area does not start a new line

### ISSUE THREAD

**Issue by A0135867R** [rongxin/se23_p01#22]
![product description text area](https://cloud.githubusercontent.com/assets/11241264/6881095/ad38df66-d58b-11e4-8e72-55bf0a9c5022.PNG)

**Comment by rongxin** [comment]
now wrap the lines for product description field.
ready for verification.

**Comment by RobinCher** [comment]
![capture](https://cloud.githubusercontent.com/assets/328109/6899965/431ff720-d736-11e4-92bf-b8b3d97eb7db.PNG) 

Verified here too
