### ISSUE TITLE
There is no verification on dates entered by user, on report screen

### ISSUE THREAD

**Issue by A0135867R** [rongxin/se23_p01#24]
There should be verifications as follows:
1. date format must be dd/MM/YYYY, alert user otherwise
2. start date must be before end date
3. start date and end date must be past date

![transaction report date verification](https://cloud.githubusercontent.com/assets/11241264/6881159/5a6a4dda-d58e-11e4-9e46-93d5c541becf.PNG)

**Comment by oscaraya** [comment]
Fixed, please review
