### ISSUE TITLE
Add Member

### ISSUE THREAD

**Issue by oscaraya** [rongxin/se23_p01#26]
When trying to add Member Oscar with card number 1111, the application display an error invalid ID which looks correct but inmediately after it display a null pointer exception at MemberTableModel.java:17

**Comment by oscaraya** [comment]
Rongxin, I think this happens on every table after the pop-up. Do you want me to help on this?

**Comment by rongxin** [comment]
I will take a look, thanks Oscar.

**Comment by rongxin** [comment]
once exception happen, I will not refresh the table data.

**Comment by rongxin** [comment]
fixed and ready for verification.

**Comment by oscaraya** [comment]
Rongxin, you finish this item.
I was planning to help you on it!!!.
Lol
