### ISSUE TITLE
Make Purchase - Scan Bar code window should close after click "Return" button. 

### ISSUE THREAD

**Issue by suhhgd** [rongxin/se23_p01#28]
1) Click "Make Purchase"
2) Click "Scan Member ID".
3) Click "Return " button. it will close "Make purchase" but Scan member ID window is still there. 
Scan member ID window should be closed once click "Return" button anytime.

**Comment by rongxin** [comment]
dispose the member scanner after finish the get member step.
ready for review.

**Comment by suhhgd** [comment]
This issue has been solved.However there is related issue. 
1) Make Payment
2 ) Scan Member
3) Scan Product barcode
4)Go Payment
5) The barcode window is still there. You still can key in bar code. The balance will change accordingly but since u can't  see items will it be better to barcode window too? 
And also is there any print button suppose to be there for receipt printing?
