### ISSUE TITLE
Member and Customer

### ISSUE THREAD

**Issue by oscaraya** [rongxin/se23_p01#3]
Hey guys, 

I have a problem here, Transaction is using Customer, not a Member, 
I cannot call reduceLoyalPoints from MemberManager because Customer may not be a Member.
Should MemberManager be a CustomerManager instead?

I also need a function increaseLoyaltyPoints, either to receive cash amount or points amount.

**Comment by A0135867R** [comment]
UI should know whether the customer is a member or not. In case of non member, loyal points shall be disabled on UI.

I would suggest to add a checkout method for non member in TransactionManager. UI should know which method to call, member_checkout or non_member_checkout. Alternatively, just add one more parameter in checkout method, to indicate it's a member or non_member.

**Comment by oscaraya** [comment]
I am not sure if that is correct, in that case he will have to maintain a flag isMember and add if isMember call this else call that. Should the nonCustomerClass have the reduceLoyalPoints as well and Throw the exception if points is more than 0?, reducing 0 point should be fine as nonCustomer always have 0 points. Customer abstract class then should request the implementation of reduceLoyalPoints to both of it's childs.

**Comment by RobinCher** [comment]
Oscar, for CustomerManager , you still have to maintain a isMember flag isn't it to differentiate if the transaction is meant for a member or not right? 

And please explain to me why the middle tier have to think about loyalty point when the customer is not even a member. Part of good UI Designs is not exposing/enabling fields that are not applicable as such.

**Comment by DancingOnAir** [comment]
I think the default customer object is the public customer,until UI gives a member infomation to the system,at that time you will know this customer is a member.
If u want to add loyal points,I can add one more function "addLoyalPoints" or combine both of them to "adjustLoyalPoints" ,u can input a positive  integer or negative integer by yourself

**Comment by oscaraya** [comment]
I agree with Tao Tong, the default is public until UI read memberID, at this moment, sent the memberID to the transaction Manager so it attach to the transaction, the method will return boolean (or a message state success or fail) The UI will then update the panel accordingly but it will not keep flag at all. Customer Manager cannot have flag neither because it is a singleton class it doesn't have attrbutes. 

I think this is the most OO, but you can correct me if I am wrong.
I think UI should call a single function End Transaction (The Customer object is inside Transaction)
TransactionManager then call the functions to update their loyal points accordingly.
From my perspective the function adjustLoyalPoints should be in all Customer childs.

Member {
   adjustLoyalPoints(quantity){
      if quantity > this.loyal 
          throw exception (Member doesn't have enough points)
      else
         update quantity
}

Non-Member {
   adjustLoyalPoints(quantity){
      if quantity > 0 {
          throw exception (sorry, public cannot pay with loyal points)
   }
}

If UI agrees to call 2 different methods to end Transaction, I am fine with that, but I don't think this is the correct way to do it.

Tao, thanks for the adjustLoyalPoints, I am then keeping the CASH_TO_POINTS constant and convert the value before passing to you.

**Comment by RobinCher** [comment]
Do whichever make your code work and its best practice. Thanks

**Comment by rongxin** [comment]
If there's way to use only one method by UI by making use of OO, it is better.
