### ISSUE TITLE
Add Discount and Question. 

### ISSUE THREAD

**Issue by suhhgd** [rongxin/se23_p01#31]
Add discount integration haven't done. 
Is Discount data are editable? Are we already had this feature or not going to have it.. I think it is part of requirement?

**Comment by RobinCher** [comment]
I think this is already implemented and there's a duplicate issues at #20

**Comment by rongxin** [comment]
will implement discount edit feature.

**Comment by DancingOnAir** [comment]
create a new method named "addDiscount" in DiscountManager already

**Comment by RobinCher** [comment]
Edit Discount is implemented , refer to below when i attempt to change the Member_First discount to 25%
![capture](https://cloud.githubusercontent.com/assets/328109/6964230/be6c6bda-d979-11e4-98cb-e045290fa24c.PNG)

Updated Discount rate for Member_First
![capture2](https://cloud.githubusercontent.com/assets/328109/6964246/de73a8a8-d979-11e4-91ff-bc62d44d30e5.PNG)
