### ISSUE TITLE
"Could not get discount" in make purchase. is it necessary to pop up every item scanning? 

### ISSUE THREAD

**Issue by suhhgd** [rongxin/se23_p01#32]
![discount](https://cloud.githubusercontent.com/assets/11241099/6896087/efe05594-d719-11e4-98c9-bdc6aeb9d27d.png)

**Comment by oscaraya** [comment]
From issue #33 
Make sure no discount applies in the discount file, make a new purchase and select non-member.
Scan a product, message will pop-up "Could not get discount"

**Comment by rongxin** [comment]
Not sure if it is still a issue, please check again.

**Comment by suhhgd** [comment]
yes. the issue still there.

**Comment by DancingOnAir** [comment]
now, if no discount applies to the customer,it will give a default discount which discount percentage is 0
