### ISSUE TITLE
Integration needed when click "Order" in Low Stock products

### ISSUE THREAD

**Issue by suhhgd** [rongxin/se23_p01#34]
I can help to create UI if you give me some framework of UI what are the fields and controls. 
![order](https://cloud.githubusercontent.com/assets/11241099/6896572/56385d32-d71f-11e4-9a6a-587688e420f2.png)

**Comment by rongxin** [comment]
Thanks Su, the purchase order function just implemented.
If you want to help, you can take a look and improve the look and feel of the purchase order (it is using html)

**Comment by suhhgd** [comment]
LOL. nothing to improve. very good ady. Just add Print Button or Send Email. (fake ) just response send successfully and close?

**Comment by suhhgd** [comment]
Question. after order , is it suppose to be restocked ? change stock balance? i find it's out of scope.
