### ISSUE TITLE
Click "Add discount" multiple times, there are multiple pop-up windows

### ISSUE THREAD

**Issue by A0135867R** [rongxin/se23_p01#35]
![multiple windows add discount](https://cloud.githubusercontent.com/assets/11241264/6897548/0674c260-d727-11e4-803d-bae8e9edabef.PNG)

**Comment by rongxin** [comment]
now prevented add discount dialogue to open multiple times.

**Comment by rongxin** [comment]
ready for review.

**Comment by A0135867R** [comment]
still happens

**Comment by rongxin** [comment]
fixed again, ready for verification.
