### ISSUE TITLE
Quantity verification for adding a product is wrong

### ISSUE THREAD

**Issue by A0135867R** [rongxin/se23_p01#37]
![quantity verification](https://cloud.githubusercontent.com/assets/11241264/6899651/84281b46-d734-11e4-9c6a-a17770c87621.PNG)

**Comment by A0135867R** [comment]
I don't understand why the quantity of 10 is invalid.

**Comment by rongxin** [comment]
fixed the number validation, forgot to add a "!" for the condition.

**Comment by rongxin** [comment]
Ready for verification.
