### ISSUE TITLE
Display of purchase order

### ISSUE THREAD

**Issue by A0135867R** [rongxin/se23_p01#38]
Not sure if it is correct to display price and total price. The price should be different from the retail price.

![purchase order](https://cloud.githubusercontent.com/assets/11241264/6899837/72e9b8e8-d735-11e4-86b0-3067f10105a4.PNG)

**Comment by rongxin** [comment]
We don't have a retail price, so probably I just remove it from the purchase order form.

**Comment by rongxin** [comment]
Removed product price and total price from the purchase form.
added category and barcode information.

Ready for review.
