### ISSUE TITLE
Redeem button should be disabled after first click or change point value to zero to make it not redeemable

### ISSUE THREAD

**Issue by suhhgd** [rongxin/se23_p01#39]
1 ) Make purchase
2 ) scan item
3) click redeem. 
If you keep on click "Redeem" the cash payable amount change until 0.00 and transaction consider success.

**Comment by oscaraya** [comment]
Wish life could be like this.
Redeem  'til you drop.

**Comment by rongxin** [comment]
Now do not allow accumulated points redeem. that means it will not add on to the previous click.
ready for verification.
