### ISSUE TITLE
barcodeNumber 

### ISSUE THREAD

**Issue by RobinCher** [rongxin/se23_p01#4]
Hi all,

Just to share that attribute : barcodeNumber under Product model is cast as a String, which is not correct as per industry standard. I will recast it as a long if there are no strong objections.

**Comment by A0135867R** [comment]
String will be more extensible, since barcode will not be used in calculation anyway.

**Comment by RobinCher** [comment]
Ok then, then i shouldn't make any changes. Just to check if we might have cast this field wrongly.
