### ISSUE TITLE
UI Display Discount Amount 

### ISSUE THREAD

**Issue by DancingOnAir** [rongxin/se23_p01#41]
![untitled](https://cloud.githubusercontent.com/assets/6667361/6917334/1983e1d8-d7d6-11e4-965a-a85bcce98f99.jpg)
Previously,Discount amount display with "-",it's very confused,I changed it with "(" & ")".

**Comment by RobinCher** [comment]
Its looks better ,more in line with accounting entry standard

**Comment by RobinCher** [comment]
@rongxin and @DancingOnAir  , Discounted amount is the amount after deducting from the discount? This is with regards to Suh question at #44 .
