### ISSUE TITLE
I don't know how to explain.

### ISSUE THREAD

**Issue by suhhgd** [rongxin/se23_p01#44]
![loyalty](https://cloud.githubusercontent.com/assets/11241099/6939342/5b88a6e0-d89e-11e4-8ad9-c22259764456.png)

**Comment by rongxin** [comment]
is the scenario "can use more points than needed?"

**Comment by RobinCher** [comment]
Looks like the Cash Payable is not reflected properly.. it should be $0.90 based on the Discount amount?

**Comment by rongxin** [comment]
total amount 1.00, after discount 0.90.
after using 100 points no need to pay any cash.
looks fine for me.

**Comment by RobinCher** [comment]
Discounted Amount should include ($0.90) bracket to show that it's a debit :). I thought it's the amount to be added.

**Comment by rongxin** [comment]
hmn... I remember it is fixed, maybe got rolledback. let me add it.

**Comment by RobinCher** [comment]
I have referenced this to #41 , which was raised by @DancingOnAir . 

Suh can you articulate the issue here? is it because Cash Payable is not reflecting?

**Comment by DancingOnAir** [comment]
I checked this scenario,when u paid discounted amount by points,it would not show u the change point,and u need to key 0 into the cash paid amount to let it checkout.

**Comment by rongxin** [comment]
hmn.. I need help on expected flow .

**Comment by suhhgd** [comment]
What i trying to say is that my loyalty point 100 which can redeem up to $5 ( Amount=Point * 0.05) . But it used up all just for $1 total balance. it should be used up 20 points only?

**Comment by oscaraya** [comment]
Can you try again?

**Comment by suhhgd** [comment]
tried. same..
