### ISSUE TITLE
Click "add vendor" multiple times, there are multiple pop-up windows

### ISSUE THREAD

**Issue by A0135867R** [rongxin/se23_p01#45]
![add vendor multiple windows](https://cloud.githubusercontent.com/assets/11241264/6942522/b482d970-d8ba-11e4-9633-9415dae62b2a.PNG)

**Comment by rongxin** [comment]
prevented multiple vendor pop up window.
ready for verify.

**Comment by RobinCher** [comment]
Tested fine, only one vendor pop up windows now

![addvendor](https://cloud.githubusercontent.com/assets/328109/6964838/7209b0f8-d97f-11e4-9e4e-1515132f9f45.PNG)

**Comment by RobinCher** [comment]
To be closed by Reporter.
