### ISSUE TITLE
Rounding of product price when adding a product

### ISSUE THREAD

**Issue by A0135867R** [rongxin/se23_p01#47]
wrong price is also saved into file.

![add product price rounding](https://cloud.githubusercontent.com/assets/11241264/6942666/b8aa8f56-d8bb-11e4-9b5e-33ea211e366b.PNG)

**Comment by RobinCher** [comment]
Test Data in JUNIT
![test](https://cloud.githubusercontent.com/assets/328109/6944076/8c28f91e-d8c4-11e4-824e-889634284384.PNG)

Saved Price in Data File
![data](https://cloud.githubusercontent.com/assets/328109/6944075/8c25c172-d8c4-11e4-93dc-e3d4586815fa.PNG)

Ready for further verification
