### ISSUE TITLE
Add discount screen: Able to select both "All" and "Member"

### ISSUE THREAD

**Issue by A0135867R** [rongxin/se23_p01#50]
![all and member](https://cloud.githubusercontent.com/assets/11241264/6942813/8fc25582-d8bc-11e4-9732-3dd9b5533b9b.PNG)

**Comment by rongxin** [comment]
Fix multiple select discount applicable type for add discount screen.
read for verification.

**Comment by RobinCher** [comment]
Multiple Select has been fixed for Add Discount

![50](https://cloud.githubusercontent.com/assets/328109/6964769/ef31a9b0-d97e-11e4-9d78-f87227726b32.PNG)
