### ISSUE TITLE
Add a product: Invalid barcode

### ISSUE THREAD

**Issue by A0135867R** [rongxin/se23_p01#52]
What is the verification on barcode?

![invalid barcode](https://cloud.githubusercontent.com/assets/11241264/6944446/4ead593e-d8c6-11e4-9b03-01147bd01e87.PNG)

**Comment by rongxin** [comment]
fixed wrong number validation, ready for validation.

**Comment by A0135867R** [comment]
what makes a valid barcode?

**Comment by rongxin** [comment]
the input barcode number is too long, I am using integer to validate as a valid number.
In this case, I will use longer data type to validate.

**Comment by rongxin** [comment]
restricted length.
ready for verify again.
