### ISSUE TITLE
Add Discount - Validation on Start Date and Discount Period

### ISSUE THREAD

**Issue by rongxin** [rongxin/se23_p01#53]
Since start date can be a date format string, and a "ALWAYS" string, and discount period can be number string and "ALWAYS" string, now add discount screen throws validation on these two fields.

Want to check
* What is the expected input and format from UI?

**Comment by DancingOnAir** [comment]
For member discount ,I think the startDay and period should be ALWAYS automatically,
For public discount,the startDay and period should not be ALWAYS.

**Comment by RobinCher** [comment]
Validation Error if i put ALWAYS for startDay and Period for Member Discount

I have yet to logged this as a bug as it could be out of scope. 

![err](https://cloud.githubusercontent.com/assets/328109/6969077/690d67e6-d99e-11e4-8ed2-062579e395ed.PNG)

**Comment by DancingOnAir** [comment]
Fixed this reformat data error for "ALWAYS" already

**Comment by RobinCher** [comment]
Ok, i will lodge the following condition into the report upon testing.

1)For member discount ,I think the startDay and period should be ALWAYS automatically,
2)For public discount,the startDay and period should not be ALWAYS.

**Comment by RobinCher** [comment]
Comments for below scenario

1)For member discount ,I think the startDay and period should be ALWAYS automatically, (Working Fine)
Adding Member Discount Screens :
![mem_discount1](https://cloud.githubusercontent.com/assets/328109/6978300/5f68e260-da02-11e4-94bf-9e0b1b7c22e5.PNG)
![mem_discount2](https://cloud.githubusercontent.com/assets/328109/6978302/659e6d30-da02-11e4-8443-ce0e85b4567c.PNG)

Finding : "ALWAYS" will be auto populated if the start date or period is not indicated as "ALWAYS". I can lodge this as a pre-condition in the report
![neg_mem1](https://cloud.githubusercontent.com/assets/328109/6978369/ee7588ea-da03-11e4-80f6-498e5edbf6e0.PNG)
![neg_mem2](https://cloud.githubusercontent.com/assets/328109/6978371/f46919d8-da03-11e4-8ef4-ae667f71dc91.PNG)


2)For public discount,the startDay and period should not be ALWAYS. (Working Fine)
Adding Public Discount Screens :
![add1](https://cloud.githubusercontent.com/assets/328109/6978291/40f53298-da02-11e4-87c6-60a774ac0bc0.PNG) 
![add2](https://cloud.githubusercontent.com/assets/328109/6978292/46de3fa6-da02-11e4-982a-ecfbd611d3fb.PNG)

Finding : Adding is fine, but still need to lodge the pre-condition for adding a Public discount is that the period and start date cannot be always, if not validation would show the following
![err](https://cloud.githubusercontent.com/assets/328109/6978330/2c240780-da03-11e4-9a5b-92ca7ef97e51.PNG)

I will assign this to @rongxin requestor to close the case.

**Comment by rongxin** [comment]
Thanks! I will close this issue.
