### ISSUE TITLE
Add Discount Start Date Invalid and NullPointer

### ISSUE THREAD

**Issue by RobinCher** [rongxin/se23_p01#55]
Start Date Invalid or NullPointerException for during adding of discount

1)Invalid Start Date (This date is pre-populated)
![err1](https://cloud.githubusercontent.com/assets/328109/6964440/b5fd7ce4-d97b-11e4-91b2-de14e0dba8d9.PNG)

2)NullPointer for other dates i selected ( i tried 02/5/2014 and 02/4/2014)
![err2](https://cloud.githubusercontent.com/assets/328109/6964451/ce6a852e-d97b-11e4-9411-120a318106e5.PNG)

I believe we only can take it the first day of a month, and there should be a check to see if today is the first day of the month, if not the start date should be 01/current month + 1.

We should ignore the year for now.

**Comment by RobinCher** [comment]
Reference #53  @rongxin

**Comment by DancingOnAir** [comment]
Previous version I set startDay should be after current day,now I relax the requirement of startDay

**Comment by RobinCher** [comment]
Fixed  
1) Add Discount for ALL 
2) Add Discount for Member (Only restricted to Member_FIRST and Member_SEQ Discount code)
