### ISSUE TITLE
Retrieving product object upon check out (via Barcode or ProductId?)

### ISSUE THREAD

**Issue by RobinCher** [rongxin/se23_p01#6]
Hi all,

When we invoke method Product.getProductManager().adjustQuantity(Product product, int quantity) to adjust a product's quantity, do we retrieve the existing product  based on the productid or/and barcode number? 

Both will be fine, but as of current implementation of ProductManager the project is being retrieved based on it's productid.

Thoughts?

**Comment by rongxin** [comment]
checkout needs to find by barcode number i think
