### ISSUE TITLE
[Question] Calculate cash to pay for loyalty points

### ISSUE THREAD

**Issue by rongxin** [rongxin/se23_p01#7]
Hi Oscar, I have a question.
When I tried to calculate the cash to pay, for total amount $10.5, redeem 50 points. the return is 0.
Looks like the calculation is not 10 points = $1?

Want to ask if it looks fine.

**Comment by oscaraya** [comment]
Hi Rongxin, 
Will check on that tonight.
Thanks!!!

**Comment by oscaraya** [comment]
Hi Rongxin, I disable the 100 based validation for the method.
The correct rate is 100 points = $5
in this case 50 points should be equal to $2.5
As your final price is 10.5, the method should return 8.
I just commit the changes, please test on it.

thanks!!!

**Comment by rongxin** [comment]
Thanks Oscar, I just tried, seems for 10.5 final price, if I input 50 points, return is 0 :(
You can try from the UI as well.
